### ISSUE TITLE
GPRS_Pro: Setting Content Type in HTTP requests (for posting JSON)

### ISSUE THREAD

**Issue by akofoed** [Libelium/waspmoteapi#11]
Hi Libelium,

I desperately need to be able to post json data to a web service using my SIM900 GPRO_Pro waspmote system. However, Content-Type has been hardcoded to x-www-form-urlencoded:
```
const char AT_HTTP_PARA_CONT[]	PROGMEM = "+HTTPPARA=\"CONTENT\",\"application/x-www-form-urlencoded\"";			//11
```
and there is no way to set it differently.
I tried setting it like this in the code with no success (compile error) (yes, I know, it's a const!):
```
GPRS_Pro.table_HTTP[11] = "+HTTPPARA=\"CONTENT\",\"application/json\"";
```

Next I have tried to use the TCP (non-transparant) and do the HTTP posting manually (setting headers etc) using a char[] but it does not not seem work.

Do you have an example how to get it to work ?

Kind regards
Anders

**Comment by Libelium** [comment]
Hi akofoed,

The standard way of communication with our support team is trough the Libelium forum. Would you mind to ask your questions there? Our colleagues will be happy to answer you as soon as possible.

www.libelium.com/forum

Best Regards.

**Comment by akofoed** [comment]
Issue posted here:
https://www.libelium.com/forum/viewtopic.php?f=16&t=16147
/A
