### ISSUE TITLE
This repository is pretty much outdated 

### ISSUE THREAD

**Issue by mausquirk** [Libelium/waspmoteapi#19]
Be aware and do not use the code from this repository!

Latest version available here is v023 whereas Libelium distributes v026 in zip-deployment on their [website](http://www.libelium.com/development/waspmote/sdk_applications/). To make the mess perfect Libelium still links the old repository alongside the new download (see [SDK download page](http://www.libelium.com/development/waspmote/sdk_applications/)).

@Libelium: please update this repository or to take it off-line. It's just bad publicity otherwise.

**Comment by Libelium** [comment]
Hi  mausquirk,

The repository has been updated to the last version v026.

Regards
