### ISSUE TITLE
Typo in WaspUtils.cpp

### ISSUE THREAD

**Issue by jdavid** [Libelium/waspmoteapi#20]
https://github.com/Libelium/waspmoteapi/blob/5ded843b9aa6401fd132a437e1b3ac5b4ae2da94/waspmote-api/WaspUtils.cpp#L719

Shouldn't this line read:

    bool flag = WaspRegister & REG_3V3;

The way it is it will always evaluate to true.

**Comment by Libelium** [comment]
Hi jdavid,

Thanks for your message, it seems you're right, we will take a look into our library to correct it.

Regards

**Comment by jdavid** [comment]
This has been fixed in v029
