### ISSUE TITLE
Possible typo in WaspUSB::OFF

### ISSUE THREAD

**Issue by jdavid** [Libelium/waspmoteapi#21]
https://github.com/Libelium/waspmoteapi/blob/5ded843b9aa6401fd132a437e1b3ac5b4ae2da94/waspmote-api/WaspUSB.cpp#L87

There is exactly the same line in ``WaspUSB::ON``, see

https://github.com/Libelium/waspmoteapi/blob/5ded843b9aa6401fd132a437e1b3ac5b4ae2da94/waspmote-api/WaspUSB.cpp#L58

I don't know exactly what this does, but logic says me it should be the opposite, if it's ``LOW`` in ``USB.ON()`` it should be ``HIGH`` in ``USB.OFF()``. No?

**Comment by Libelium** [comment]
Hi,

**digitalWrite(XBEE_MON,LOW)** is correct in both cases. This line was implemented to avoid interferences when multiplexer was used. It only applies to Waspmote v12, those lines could be comment out if you are working with Waspmote v15.

Regards

**Comment by jdavid** [comment]
Thanks.
