### ISSUE TITLE
Bug in TwoWire::secureBegin

### ISSUE THREAD

**Issue by jdavid** [Libelium/waspmoteapi#23]
https://github.com/Libelium/waspmoteapi/blob/5ded843b9aa6401fd132a437e1b3ac5b4ae2da94/waspmote-api/Wire.cpp#L383

This is the code:

	if (((WaspRegisterSensor & REG_EVENTS)||(WaspRegisterSensor & REG_AMBIENT)) && !_3V3_ON)
	{
		PWR.setSensorPower(SENS_3V3, SENS_ON);		
		delay(50);		
	}
	else if (!_5V_ON || !_3V3_ON)
	{
		PWR.setSensorPower(SENS_3V3, SENS_ON);
		PWR.setSensorPower(SENS_5V, SENS_ON);	
		delay(50);						
	}

The bug happens when: (1) use an events or ambient board, (2) 3V3 is on, and (3) 5V is off. Then the code will go through the second block, and turn on 5V, what it should not.

I think the correct code should read like this:

	if ((WaspRegisterSensor & REG_EVENTS)||(WaspRegisterSensor & REG_AMBIENT))
	{
		if (!_3V3_ON)
		{
			PWR.setSensorPower(SENS_3V3, SENS_ON);		
			delay(50);		
		}
	}
	else if (!_5V_ON || !_3V3_ON)
	{
		PWR.setSensorPower(SENS_3V3, SENS_ON);
		PWR.setSensorPower(SENS_5V, SENS_ON);	
		delay(50);						
	}

**Comment by Libelium** [comment]
Hi David,

It seems you are right. We are going to consider including it in the next API release.

Thanks for your contribution.

Regards

**Comment by jdavid** [comment]
This bug is still present in v029

**Comment by Libelium** [comment]
Hi jdavid,
Thanks again for your contribution.
Notice this is a minor bug and we had no time to check it and include it at the new API v029.
We hope to be fixed on the next API.
Regards.

**Comment by jdavid** [comment]
See this has been fixed in v030, closing.
