### ISSUE TITLE
Infinite loop in GPS.ON if not GPS module

### ISSUE THREAD

**Issue by jdavid** [Libelium/waspmoteapi#24]
https://github.com/Libelium/waspmoteapi/blob/5ded843b9aa6401fd132a437e1b3ac5b4ae2da94/libraries/GPS/WaspGPS.cpp#L287

I am trying to autodetect whether the GPS module is there or not:

    hasGPS = GPS.ON();
    GPS.OFF();

Problem is there is an infinite loop in ``GPS.ON``: ``ON`` calls ``init``, at the end the ``valid`` variable is false, so ``ON`` is called again, and so on.

Which would be the correct way to fix this? So I don't have to wait for a new version of the API to be released.

**Comment by Libelium** [comment]
Hi,

We fixed that bug few days ago. You have to remove ON(); inside init() function
```
	// Ensure that module is in NMEA mode by default
	if(!valid) 
	{
		#ifdef GPS_DEBUG
		USB.println(F("init command not found."));
		#endif
		OFF();
	}
```
Now GPS.ON() function should return 1 if the module is plugged on Waspmote and 0 if not.

Regards

**Comment by jdavid** [comment]
Thanks!

**Comment by jdavid** [comment]
I see this has been fixed in the v029, thanks.
