### ISSUE TITLE
Bug in RTC.readRTC since v033

### ISSUE THREAD

**Issue by jdavid** [Libelium/waspmoteapi#34]
For instance this function is called like this:

```cpp
char* WaspRTC::getTime()
{
        readRTC(RTC_DATE_ADDRESS_2);
        return getTimestamp();
}
```

Where the value of the constant is:

```cpp
#define RTC_DATE_ADDRESS_2              6
```

Now the code of `readRTC()`:

```cpp
                for (int i = 0; i < endAddress; i++)
                {
                        registersRTC[i] = data[i];
                        switch (i)
                        {
                                case 0: second = BCD2byte(data[i]>>4, data[i]&B00001111);
                                                break;
                                [...]
                                case 5: month = BCD2byte(data[i]>>4, data[i]&B00001111);
                                                break;
                                case 6: year = BCD2byte(data[i]>>4, data[i]&B00001111);
                                                break;
                                [...]
```

Here the value of `endAddress` is 6, so `readRTC` will never set the year.

It looks to me that the correct solution would be to increment the value of the 3 affected constants. Then
it would be possible to use these constants in other places, for example the value `7` is hardcoded in `writeRTC`

The bug is there since the logic in `readRTC` was changed in commit a6072a027e55

**Comment by Libelium** [comment]
Thanks for your contribution one more time.

It will be corrected in the the API release.

Regards.

**Comment by jdavid** [comment]
I see this has been fixed in v038, closing.
