### ISSUE TITLE
WaspBG96 boot looping on power-on during ON() function.

### ISSUE THREAD

**Issue by PhatHub** [Libelium/waspmoteapi#50]
Currently I'm using the Libelium waspmote with the BG96 modem. It is connected to the 6600mAh battery pack.

I'm having an intermittent issue, where the device will work once every 20-50 times. 

I have narrowed it down to when the GPRS is turned on [here in ON()](https://github.com/Libelium/waspmoteapi/blob/02591a22909666d51409765f232efe206659ea01/libraries/BG96/WaspBG96.cpp#L1284) and for some reason it will crash the sketch and cause a boot loop some time in the middle of the 1000ms delay in the next line. 

This seems like it might be a power issue? Does the "PWM" phase of powering on (lines 1277-1283) require more time?

Thank you.

**Comment by PhatHub** [comment]
Issue resolved. Battery wires were too thin, and wires to bypass the power switch (to make an external switch) were too thin as well. 
I shortened the switch wires to reduce resistance, and it is slightly more stable, I'll have to replace it with a thicker gauge later on.

**Comment by biagioboi** [comment]
Sorry for writing here, but i didn't found any email address to write you. I have the same problem with my Waspmote v15 connected with WaspBG96 can you write me the schema to follow to activate correctly the board in order to prevent the infinite loop
