### ISSUE TITLE
TSL2561 wrong readings in bright light (P&S Smart Agriculture Xtreme)

### ISSUE THREAD

**Issue by andikulla** [Libelium/waspmoteapi#54]
#### Summary
Reading the luminosity sensor (which uses the TSL2561) returns wrong values in bright light. Instead returning approximately 30000 to 40000 luxes, it mostly reads 384 luxes. Sometimes the value goes slightly up to little above 400 luxes but mostly sticks to 384 luxes. Readings in dimmer light up to approx. 25000 seem to be correct. This issue also appears using the example code provided by Libelium [here](https://development.libelium.com/ag-xtr-17-tsl2561-sensor-reading/).
(The TSL2561 Library included in the Waspmote IDE is identical to the library in this repo (Version 3.3, 2018))

#### How to reproduce
- Install the luminosity sensor to port A of the Plug&Sense Smart Agriculture Xtreme
- Write the [example code](https://development.libelium.com/ag-xtr-17-tsl2561-sensor-reading/) provided by Libelium to the P&S / µC without changing the code
- Read the values via serial port

#### Background Information
- Hardware: Waspmote Plug&Sense Smart Agriculture Xtreme LoRaWAN EU Version 1.0
- IDE: Waspmote Pro IDE v06.29

**Comment by Libelium** [comment]
Hi,
To solve your issue, please contact our colleagues from technical service here: https://www.libelium.com/contact/
Thank you.
